### PR TITLE
#39 - Rename templates

### LINKED ISSUE #39: Template name changes
I think we should revise some of the template names:

 * `WebSharper 6 Extension` -> `WebSharper 6 JavaScript Bindings` - the idea being that "bindings" is a more generally understood term than "extension", which itself never really took off
 * `WebSharper 6 Proxy` -> `WebSharper .NET Proxy` - the idea is to make it more clear that a "proxy" is .NET->JS
 * `WebSharper 6 Html Site` -> `WebSharper 6 HTML Application` - since we have "Application" in the other application template names
 * `WebSharper 6 Single Page Application` -> `WebSharper 6 Single-Page Application` - to correct the grammar

### PR DESCRIPTION
**Pull request by Jooseppi12**
Fix #39

### CODE REVIEW

**Comment by Jooseppi12** [comment]
@granicz With the change from `WebSharper X Extension` to `WebSharper X Javascript Bindings` do we want to change the short name as well from `websharper-ext`?

**Comment by granicz** [comment]
The short code can stay IMHO, we still kind of want to reinforce the terminology that these are "extensions".

**Comment by granicz** [comment]
Did you miss renaming the HTML application template?

**Comment by Jooseppi12** [comment]
Indeed, I missed those, now they are added.

**Pull request merged**
